services:
    app:
        build:
            context: .
            dockerfile: deploy/app/workspace.Dockerfile
        container_name: milty-app
        restart: unless-stopped
        tty: true
        working_dir: /code
        networks:
            - backend
        ports:
            - "${DOCKER_HTTP_PORT:-80}:80"
        volumes:
            - ./:/code:delegated
            - ./deploy/app/php/php.ini:/usr/local/etc/php/conf.d/php.ini
networks:
    backend:
        driver: bridge